"""add billing and admin fields

Revision ID: 073ce17c17dc
Revises: 631f598d049a
Create Date: 2026-08-02 21:21:05.436371

Além dos campos novos (cobrança via Asaas, flag de admin da plataforma),
esta migração estende o RLS com duas políticas adicionais (permissivas,
somadas por OR às que já existem — ver 631f598d049a):

  - Bypass de admin: quando app.platform_admin = 'true' (setado só por
    get_current_admin, depois de confirmar is_platform_admin=True), o
    painel administrativo interno enxerga todas as empresas/lojas/
    usuários. Sem isso, /v1/admin/companies sempre voltaria vazio.
  - Lookup do webhook de cobrança: o Asaas chama /v1/billing/webhook sem
    usuário logado — libera achar/atualizar só a empresa dona da
    assinatura informada (app.lookup_subscription_id), igual ao padrão já
    usado para a API key da loja e o token de convite.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '073ce17c17dc'
down_revision = '631f598d049a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted por segurança ###
    # subscription_status e is_platform_admin são expostos como campos
    # obrigatórios (não Optional) em AdminCompanyOut/MeOut — sem um
    # server_default, empresas/usuários já existentes ficariam com NULL
    # e quebrariam a serialização dessas respostas.
    op.add_column('companies', sa.Column('asaas_customer_id', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('asaas_subscription_id', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('subscription_status', sa.String(), nullable=False, server_default='none'))
    op.add_column('users', sa.Column('is_platform_admin', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###

    # --- extensão do RLS: bypass do painel admin (visão cross-empresa) ---
    op.execute("""
        CREATE POLICY companies_admin_bypass ON companies
        FOR SELECT USING (current_setting('app.platform_admin', true) = 'true')
    """)
    op.execute("""
        CREATE POLICY stores_admin_bypass ON stores
        FOR SELECT USING (current_setting('app.platform_admin', true) = 'true')
    """)
    op.execute("""
        CREATE POLICY users_admin_bypass ON users
        FOR SELECT USING (current_setting('app.platform_admin', true) = 'true')
    """)

    # --- extensão do RLS: webhook de cobrança (sem usuário logado) ---
    op.execute("""
        CREATE POLICY companies_billing_webhook ON companies
        FOR SELECT USING (
            asaas_subscription_id = NULLIF(current_setting('app.lookup_subscription_id', true), '')
        )
    """)
    op.execute("""
        CREATE POLICY companies_billing_webhook_update ON companies
        FOR UPDATE USING (
            asaas_subscription_id = NULLIF(current_setting('app.lookup_subscription_id', true), '')
        )
    """)


def downgrade():
    op.execute("DROP POLICY IF EXISTS companies_billing_webhook_update ON companies")
    op.execute("DROP POLICY IF EXISTS companies_billing_webhook ON companies")
    op.execute("DROP POLICY IF EXISTS users_admin_bypass ON users")
    op.execute("DROP POLICY IF EXISTS stores_admin_bypass ON stores")
    op.execute("DROP POLICY IF EXISTS companies_admin_bypass ON companies")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_platform_admin')
    op.drop_column('companies', 'subscription_status')
    op.drop_column('companies', 'asaas_subscription_id')
    op.drop_column('companies', 'asaas_customer_id')
    # ### end Alembic commands ###
