"""add prepaid checkouts

Revision ID: 1def4146e621
Revises: 7c15c0125e5d
Create Date: 2026-08-07 13:53:18.519871

Tabela nova pro fluxo de aquisição por link de marketing (paga antes de
existir conta). RLS segue o mesmo princípio de team_invites/
password_reset_tokens (posse do token = credencial), com um lookup
adicional por asaas_checkout_id pro webhook conseguir achar o registro
sem depender de um company_id que ainda não existe.

Diferente de 304dfa099fac/7c15c0125e5d: desta vez já nasce com as
policies de UPDATE cobrindo os dois lookups desde o início (aprendido
testando o heartbeat/onboarding — SELECT sem o UPDATE correspondente
falha silenciosamente, SQLAlchemy acusa StaleDataError "0 rows matched").
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1def4146e621'
down_revision = '7c15c0125e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prepaid_checkouts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('asaas_checkout_id', sa.String(), nullable=False),
    sa.Column('claim_token', sa.String(), nullable=False),
    sa.Column('camera_packages', sa.Integer(), nullable=False),
    sa.Column('monthly_value', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('asaas_customer_id', sa.String(), nullable=True),
    sa.Column('asaas_subscription_id', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('claimed_company_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claimed_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asaas_checkout_id'),
    sa.UniqueConstraint('claim_token')
    )
    # ### end Alembic commands ###

    # --- Row Level Security ---------------------------------------------
    op.execute("""
        DO $$
        BEGIN
            IF (SELECT rolsuper FROM pg_roles WHERE rolname = current_user) THEN
                RAISE EXCEPTION
                    'Role de conexao "%" e superuser -- RLS seria ignorado silenciosamente. '
                    'Use uma role sem superuser antes de aplicar esta migracao.',
                    current_user;
            END IF;
        END $$;
    """)

    op.execute("ALTER TABLE prepaid_checkouts ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE prepaid_checkouts FORCE ROW LEVEL SECURITY")

    op.execute("""
        CREATE POLICY prepaid_checkouts_lookup_select ON prepaid_checkouts
        FOR SELECT USING (
            claim_token = NULLIF(current_setting('app.lookup_prepaid_token', true), '')
            OR asaas_checkout_id = NULLIF(current_setting('app.lookup_prepaid_checkout_id', true), '')
            OR current_setting('app.platform_admin', true) = 'true'
        )
    """)
    op.execute("""
        CREATE POLICY prepaid_checkouts_lookup_update ON prepaid_checkouts
        FOR UPDATE USING (
            claim_token = NULLIF(current_setting('app.lookup_prepaid_token', true), '')
            OR asaas_checkout_id = NULLIF(current_setting('app.lookup_prepaid_checkout_id', true), '')
        )
    """)
    op.execute("""
        CREATE POLICY prepaid_checkouts_insert ON prepaid_checkouts
        FOR INSERT WITH CHECK (true)
    """)


def downgrade():
    op.execute("DROP POLICY IF EXISTS prepaid_checkouts_insert ON prepaid_checkouts")
    op.execute("DROP POLICY IF EXISTS prepaid_checkouts_lookup_update ON prepaid_checkouts")
    op.execute("DROP POLICY IF EXISTS prepaid_checkouts_lookup_select ON prepaid_checkouts")
    op.execute("ALTER TABLE prepaid_checkouts NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE prepaid_checkouts DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prepaid_checkouts')
    # ### end Alembic commands ###
