"""add camera package billing fields

Revision ID: 2c999006f372
Revises: 073ce17c17dc
Create Date: 2026-08-03 12:41:13.615786

Além dos dois campos novos em companies (camera_limit,
pending_camera_packages), esta migração estende o RLS com duas
políticas adicionais (permissivas, somadas por OR às que já existem):

  - Bypass de admin pra cameras: list_companies (admin.py) agora conta
    cameras_used via join com stores — sem essa política, o RLS
    esconderia todas as linhas de cameras do painel admin (só existia
    bypass pra companies/stores/users até aqui).
  - Lookup do webhook por customer_id: o billing.py agora tem um
    segundo caminho pra achar a empresa no webhook (cobrança avulsa de
    upgrade não tem "subscription", só "customer") — precisa da mesma
    liberação pontual que já existia pra subscription_id.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c999006f372'
down_revision = '073ce17c17dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted por segurança ###
    # server_default: sem isso, adicionar uma coluna NOT NULL numa
    # tabela que já tem linhas (empresas existentes) falha na hora —
    # elas ficam com camera_limit=0 (sem nenhum pacote contratado ainda).
    op.add_column('companies', sa.Column('camera_limit', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('companies', sa.Column('pending_camera_packages', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    op.execute("""
        CREATE POLICY cameras_admin_bypass ON cameras
        FOR SELECT USING (current_setting('app.platform_admin', true) = 'true')
    """)
    op.execute("""
        CREATE POLICY companies_billing_webhook_by_customer ON companies
        FOR SELECT USING (
            asaas_customer_id = NULLIF(current_setting('app.lookup_customer_id', true), '')
        )
    """)
    op.execute("""
        CREATE POLICY companies_billing_webhook_by_customer_update ON companies
        FOR UPDATE USING (
            asaas_customer_id = NULLIF(current_setting('app.lookup_customer_id', true), '')
        )
    """)


def downgrade():
    op.execute("DROP POLICY IF EXISTS companies_billing_webhook_by_customer_update ON companies")
    op.execute("DROP POLICY IF EXISTS companies_billing_webhook_by_customer ON companies")
    op.execute("DROP POLICY IF EXISTS cameras_admin_bypass ON cameras")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'pending_camera_packages')
    op.drop_column('companies', 'camera_limit')
    # ### end Alembic commands ###
