"""add password reset tokens

Revision ID: 324f2a09bfc2
Revises: 2c999006f372
Create Date: 2026-08-05 23:37:49.913229

Tabela nova para o fluxo de "esqueci minha senha", com RLS seguindo
exatamente o mesmo padrão já usado para team_invites (ver 631f598d049a):
isolamento por company_id para quem já está logado, OR lookup pontual
pela posse do token (app.lookup_reset_token) para os dois endpoints
públicos de recuperação de senha, onde quem chama ainda não conseguiu
entrar na própria conta.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324f2a09bfc2'
down_revision = '2c999006f372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###

    # --- Row Level Security (mesmo padrão de team_invites) --------------
    # Guard: mesma checagem de 631f598d049a — RLS é ignorado em silêncio
    # se a role de conexão for superuser.
    op.execute("""
        DO $$
        BEGIN
            IF (SELECT rolsuper FROM pg_roles WHERE rolname = current_user) THEN
                RAISE EXCEPTION
                    'Role de conexao "%" e superuser -- RLS seria ignorado silenciosamente. '
                    'Use uma role sem superuser antes de aplicar esta migracao.',
                    current_user;
            END IF;
        END $$;
    """)

    op.execute("ALTER TABLE password_reset_tokens ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE password_reset_tokens FORCE ROW LEVEL SECURITY")

    op.execute("""
        CREATE POLICY password_reset_tokens_tenant_isolation ON password_reset_tokens
        FOR SELECT USING (
            company_id = NULLIF(current_setting('app.current_company_id', true), '')::uuid
            OR token = NULLIF(current_setting('app.lookup_reset_token', true), '')
        )
    """)
    op.execute("""
        CREATE POLICY password_reset_tokens_tenant_modify ON password_reset_tokens
        FOR UPDATE USING (
            company_id = NULLIF(current_setting('app.current_company_id', true), '')::uuid
            OR token = NULLIF(current_setting('app.lookup_reset_token', true), '')
        )
    """)
    op.execute("""
        CREATE POLICY password_reset_tokens_tenant_delete ON password_reset_tokens
        FOR DELETE USING (company_id = NULLIF(current_setting('app.current_company_id', true), '')::uuid)
    """)
    op.execute("""
        CREATE POLICY password_reset_tokens_insert ON password_reset_tokens
        FOR INSERT WITH CHECK (true)
    """)


def downgrade():
    op.execute("DROP POLICY IF EXISTS password_reset_tokens_insert ON password_reset_tokens")
    op.execute("DROP POLICY IF EXISTS password_reset_tokens_tenant_delete ON password_reset_tokens")
    op.execute("DROP POLICY IF EXISTS password_reset_tokens_tenant_modify ON password_reset_tokens")
    op.execute("DROP POLICY IF EXISTS password_reset_tokens_tenant_isolation ON password_reset_tokens")
    op.execute("ALTER TABLE password_reset_tokens NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE password_reset_tokens DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
