"""add onboarding status and heartbeat fields

Revision ID: 3a1a7d605a48
Revises: 324f2a09bfc2
Create Date: 2026-08-07 12:36:03.799314

stores.onboarding_status é NOT NULL — precisa de server_default pra não
quebrar nas lojas já existentes (mesmo motivo de subscription_status/
is_platform_admin na migração 073ce17c17dc: sem o default, as linhas
atuais ficariam com NULL e a constraint rejeitaria).
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1a7d605a48'
down_revision = '324f2a09bfc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted por segurança ###
    op.add_column('companies', sa.Column('payment_confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('stores', sa.Column('onboarding_status', sa.String(), nullable=False, server_default='pending'))
    op.add_column('stores', sa.Column('last_seen_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'last_seen_at')
    op.drop_column('stores', 'onboarding_status')
    op.drop_column('companies', 'payment_confirmed_at')
    # ### end Alembic commands ###
